run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - goimports
    - gofmt
    - misspell
    - gocritic
    - gosec

linters-settings:
  goimports:
    local-prefixes: github.com/wiruzman/cert-manager-notifier
  
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - unnamedResult
      - hugeParam
  
  gosec:
    excludes:
      - G204 # Subprocess launched with variable
      - G304 # File path provided as taint input

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - gocritic
