{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cert-manager-notifier.fullname" . }}
  labels:
    {{- include "cert-manager-notifier.labels" . | nindent 4 }}
rules:
- apiGroups: ["cert-manager.io"]
  resources: ["certificates"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cert-manager-notifier.fullname" . }}
  labels:
    {{- include "cert-manager-notifier.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cert-manager-notifier.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "cert-manager-notifier.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
